version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    user: 1000:1000
    network_mode: host
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./ingestion:/var/lib/clickhouse/user_files
      - ./clickhouse:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    restart: on-failure
