version: "3.9"

services:
  timescale:
    image: timescale/timescaledb-ha:pg16-latest
    container_name: timescale
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
        - ./postgres:/data/postgres
    ports:
      - 5432:5432
    restart: on-failure
