[project]
name = "prefect-starter"
version = "0.0.1"
description = "A starter template for running Prefect"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "faker>=35.2.0",
    "prefect>=3.1.13",
    "prefect-aws>=0.5.3",
    "prefect-docker>=0.6.2",
    "websockets>=13.1",
]
