version: "3.9"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    user: 1000:1000
    command:
      - start
      - --log
      - trace
      - --user
      - $SURREALDB_USER
      - --pass
      - $SURREALDB_PASSWORD
      - surrealkv:/data/database
    volumes:
      - ./surrealdb:/data
    ports:
      - "8000:8000"
    restart: on-failure
