version: '3.9'

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    restart: on-failure