version: "3.9"

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    environment:
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongo}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: on-failure
