version: "3.9"

services:
  couchdb:
    container_name: couchdb
    image: couchdb
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-postgres}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-password}
    volumes:
      - ./couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"
    restart: unless-stopped
