version: "3.9"

services:
  open_observe:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: open_observe
    environment:
      ZO_ROOT_USER_EMAIL: open@observe.com
      ZO_ROOT_USER_PASSWORD: password
      ZO_DATA_DIR: /data
    volumes:
      - ./open_observe:/data
    ports:
      - 5080:5080
    restart: on-failure
