version: "3.9"

services:
  scylla:
      container_name: scylla
      image: scylladb/scylla
      ports:
        - "9042:9042"
        - "9160:9160"
      volumes:
        - ./scylla:/var/lib/scylla
      restart: unless-stopped
