version: "3.9"

services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    command: --smp ${SCYLLA_CORES:-1} --developer-mode ${SCYLLA_DEVELOPER_MODE:-1}
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - ./scylla:/var/lib/scylla
    restart: on-failure
