version: '3.9'

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data
    environment:
      SSL_MODE: off
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure