version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      SSL_MODE: off
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure
