version: "3.9"

services:
  cassandra:
      image: cassandra
      container_name: cassandra
      volumes:
        - ./cassandra:/var/lib/cassandra
      ports:
        - 9042:9042
      restart: on-failure
