version: "3.9"

services:
  postgres:
    container_name: postgres-extensions
    build:
      context: .
    command: -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
       - ./postgres.conf:/etc/postgresql/postgresql.conf
       - ./init_sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
