version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass "$${REDIS_PASSWORD}"'
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    restart: on-failure